### ISSUE TITLE
Cannot load such file

### ISSUE THREAD

**Issue by verwinv** [abartov/wimgs#1]
Hi, I receive the following error message when I try to load this - could you tell what's going wrong?

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mediawiki_api (LoadError)
from     /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from wimgs.rb:11:in `<main>
```

**Comment by abartov** [comment]
Sorry I didn't notice this earlier.  The error message is saying it can't find the 'mediawiki_api' gem.  I would be inclined to believe it.  Try 'gem install mediawiki_api' and then re-run wimgs.  

If that doesn't work for you, please file a new issue.  Cheers!

**Comment by nicolas-raoul** [comment]
On Ubuntu you need to install these packages:
```
sudo apt install ruby-dev ruby-sqlite3
```
Before `sudo gem install mediawiki_api` can run successfully.
