### ISSUE TITLE
JSON::ParserError when trying to download

### ISSUE THREAD

**Issue by floli** [abartov/wimgs#2]
I try to download a category:

```
% ../wimgs/wimgs.rb --wiki commons.wikimedia.org --category "Commons featured widescreen desktop backgrounds"
Empty database created.
reading category image list... /usr/lib/ruby/2.2.0/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from /usr/lib/ruby/2.2.0/json/common.rb:155:in `new'
        from /usr/lib/ruby/2.2.0/json/common.rb:155:in `parse'
        from /home/florian/.gem/ruby/2.2.0/gems/mediawiki_api-0.4.1/lib/mediawiki_api/response.rb:97:in `response_object'
        from /home/florian/.gem/ruby/2.2.0/gems/mediawiki_api-0.4.1/lib/mediawiki_api/response.rb:46:in `data'
        from ../wimgs/wimgs.rb:118:in `category_files'
        from ../wimgs/wimgs.rb:195:in `<main>'
```

Installed sqlite3 using `gem install --user-install` and mediawiki the same way but from github.com/wikimedia/mediawiki-ruby-api.

System is ArchLinux

```
% ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

**Comment by abartov** [comment]
Hi, Florian.  

wimgs uses the older mediawiki_api gem rather than the official Wikimedia API gem.  I will rewrite it Some Day<tm> to user the newer API, but for now, you'll have to install the older gem, i.e. this one: https://github.com/jpatokal/mediawiki-gateway

Let me know if you still run into problems!

**Comment by abartov** [comment]
Oh, forgive my earlier comment.  I had completely forgotten I did already migrate this to the newer API. I will be looking at this bug later today.

**Comment by abartov** [comment]
Turns out to be simple: the Wikimedia API is now only available via HTTPS.  The code I have just pushed works (in category mode; article mode is out-of-date).
