### ISSUE TITLE
NotADatabaseException

### ISSUE THREAD

**Issue by nicolas-raoul** [abartov/wimgs#6]
```
$ ruby wimgs.rb --wiki commons.wikimedia.org --category "Images from Wiki Loves Africa 2014 in Ghana" --images-dir /home/nico/wimgs/files
Traceback (most recent call last):
        6: from wimgs.rb:197:in `<main>'
        5: from wimgs.rb:72:in `prepare_db'
        4: from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:281:in `get_first_row'
        3: from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:137:in `execute'
        2: from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:91:in `prepare'
        1: from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:91:in `new'
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:91:in `initialize': file is not a database (SQLite3::NotADatabaseException)
```

**Comment by abartov** [comment]
That's interesting!  Do you have a wimgs.db file?  Can you attach it?

Also, try renaming it away and re-running?

**Comment by nicolas-raoul** [comment]
`find ~ -name wimgs.db` finds nothing, so I can say I have no such file in my whole home.

**Comment by abartov** [comment]
Hmm, I'm stumped.  Looking at the code, the only thing I can think of that would prevent this from working is if you don't have permissions to create a file in your current working directory.

My suggestions:

1. Try installing the 'sqlite3' package (for command-line sqlite3) and running, in the same directory you're running wimgs from:
```sqlite3 wimgs.db```
If that works, it's not a permissions issue.

2. If you are familiar with command-line debugging, install the byebug gem and run:
```
byebug wimgs.rb -- --wiki commons.wikimedia.org --category "Images from Wiki Loves Africa 2014 in Ghana" --images-dir /home/nico/wimgs/files
```
and see if you can see whether the wimgs.db file gets created at all during prepare_db.

3. Finally, I'm curious enough about this problem to be willing to spend time debugging it for you, so if you're interested, reproduce it on virtual machine and give me command line access to it so I can investigate.

**Comment by nicolas-raoul** [comment]
1. Here is the result when running that command in the same directory:
```
wimgs$ sqlite3 wimgs.db
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> 
```

**Comment by abartov** [comment]
Was a typo in the default configuration. Should have been .db and not .rb of course.  Fixed, thanks!
