### ISSUE TITLE
Filename broken if contains quotes

### ISSUE THREAD

**Issue by nicolas-raoul** [abartov/wimgs#8]
1. Download category which contains the file `"Nakre Udbhava Sri Mahalingeshvara" 3.jpg`
2. It is downloaded like this (the file in the middle):

![screenshot from 2018-10-02 19-30-38](https://user-images.githubusercontent.com/99590/46343734-b122f200-c679-11e8-861d-e7c5c9734f13.png)

As you can see, the filename has become just `Nakre` without even an extension.
Many of the other files got the same problem.

**Comment by abartov** [comment]
Fixed with commit 2df8ca3
